//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchangeDeLivre.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EchangeDeLivre.Ressources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Book Exchange for log 210.
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to provide additional information..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your account type.
        /// </summary>
        public static string AccountCategoryInfo {
            get {
                return ResourceManager.GetString("AccountCategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation.
        /// </summary>
        public static string AccountCreation {
            get {
                return ResourceManager.GetString("AccountCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a book.
        /// </summary>
        public static string AddBook {
            get {
                return ResourceManager.GetString("AddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperative adress.
        /// </summary>
        public static string CoopAdress {
            get {
                return ResourceManager.GetString("CoopAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperative manager.
        /// </summary>
        public static string CoopManager {
            get {
                return ResourceManager.GetString("CoopManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperative name.
        /// </summary>
        public static string CoopName {
            get {
                return ResourceManager.GetString("CoopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you do not have a local account..
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See .
        /// </summary>
        public static string ExternalAuth1 {
            get {
                return ResourceManager.GetString("ExternalAuth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this article.
        /// </summary>
        public static string ExternalAuth2 {
            get {
                return ResourceManager.GetString("ExternalAuth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ExternalAuth3 {
            get {
                return ResourceManager.GetString("ExternalAuth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more libraries.
        /// </summary>
        public static string GetMoreLibrary {
            get {
                return ResourceManager.GetString("GetMoreLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects..
        /// </summary>
        public static string GetMoreLibraryInfo {
            get {
                return ResourceManager.GetString("GetMoreLibraryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        ///            enables a clean separation of concerns and gives you full control over markup
        ///            for enjoyable, agile development..
        /// </summary>
        public static string GettingStartedInfo {
            get {
                return ResourceManager.GetString("GettingStartedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade book system.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript..
        /// </summary>
        public static string JumboTronText {
            get {
                return ResourceManager.GetString("JumboTronText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string LanguageChoice {
            get {
                return ResourceManager.GetString("LanguageChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr-CA.
        /// </summary>
        public static string languageCode {
            get {
                return ResourceManager.GetString("languageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log on..
        /// </summary>
        public static string LocalAccount {
            get {
                return ResourceManager.GetString("LocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string OtherLoginService {
            get {
                return ResourceManager.GetString("OtherLoginService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Hosting.
        /// </summary>
        public static string TitleWebHosting {
            get {
                return ResourceManager.GetString("TitleWebHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Category.
        /// </summary>
        public static string UserCategory {
            get {
                return ResourceManager.GetString("UserCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily find a web hosting company that offers the right mix of features and price for your applications..
        /// </summary>
        public static string WebHostingInfo {
            get {
                return ResourceManager.GetString("WebHostingInfo", resourceCulture);
            }
        }
    }
}
